TEMPLATE_PARTS = """
{% macro site_header(site, navigation, language_links=()) -%}
<header class="site-header">
  <div class="masthead-mark" aria-hidden="true">ML</div>
  <div class="masthead-copy">
    <a class="site-title" href="{{ navigation.home_href }}">{{ site.title }}</a>
    <p class="site-description">{{ site.description }}</p>
  </div>
  <div class="header-actions">
    {% if language_links %}
      <details class="language-switcher">
        <summary aria-label="Choose language">
          <span class="language-switcher__label">
            {{ site.extension_setting('i18n', 'label_language', 'Language') }}
          </span>
          <span class="language-switcher__current">{{ site.locale }}</span>
        </summary>
        <ul>
          {% for link in language_links %}
            <li>
              <a
                href="{{ link.href }}"
                {% if link.current %}aria-current="page"{% endif %}
              >
                {{ link.label }}
              </a>
            </li>
          {% endfor %}
        </ul>
      </details>
    {% endif %}
    <button
      class="menu-toggle"
      type="button"
      aria-controls="site-navigation"
      aria-expanded="false"
    >
      {{ site.extension_setting('i18n', 'label_menu', 'Menu') }}
    </button>
  </div>
</header>
{%- endmacro %}

{% macro site_navigation(site, navigation, home_current=False) -%}
<aside class="sidebar" id="site-navigation">
  <nav aria-label="Primary">
    <a
      class="home-link"
      href="{{ navigation.home_href }}"
      {% if home_current %}aria-current="page"{% endif %}
    >
      {{ site.extension_setting('i18n', 'label_field_index', 'Field Index') }}
    </a>
    {% for section in navigation.sections %}
      <section class="navigation-section" aria-labelledby="section-{{ loop.index }}">
        <h2 id="section-{{ loop.index }}">
          <a href="{{ section.href }}">{{ section.title }}</a>
        </h2>
        {% if section.links %}
          <nav aria-label="{{ section.title }} contents">
            <ol>
              {% for link in section.links %}
                <li>
                  <a href="{{ link.href }}"{% if link.current %} aria-current="page"{% endif %}>
                    {{ link.label }}
                  </a>
                </li>
              {% endfor %}
            </ol>
          </nav>
        {% endif %}
      </section>
    {% endfor %}
  </nav>
</aside>
{%- endmacro %}

{% macro article_toc(site, article) -%}
{% if article.has_table_of_contents() %}
{% set toc_label = site.extension_setting('i18n', 'label_on_this_page', 'On this page') %}
<aside class="article-toc" aria-label="{{ toc_label }}">
  <p class="data-label">{{ toc_label }}</p>
  <ol>
    {% for heading in article.headings %}
      <li>
        <a class="{{ heading.depth_class() }}" href="{{ heading.href }}">{{ heading.label }}</a>
      </li>
    {% endfor %}
  </ol>
</aside>
{% endif %}
{%- endmacro %}

{% macro site_footer(site) -%}
{% set footer_text = site.extension_setting(
  'i18n',
  'footer_text',
  'Generated by the content-first static site generator.',
) %}
<footer class="site-footer">
  <p>{{ footer_text }}</p>
</footer>
{%- endmacro %}

{% macro pager(rendered_page) -%}
<nav class="pager" aria-label="Adjacent pages">
  {% if rendered_page.previous_link %}
    <a rel="prev" href="{{ rendered_page.previous_link.href }}">
      <span>{{ rendered_page.previous_link.relation }}</span>
      {{ rendered_page.previous_link.label }}
    </a>
  {% endif %}
  {% if rendered_page.next_link %}
    <a rel="next" href="{{ rendered_page.next_link.href }}">
      <span>{{ rendered_page.next_link.relation }}</span>
      {{ rendered_page.next_link.label }}
    </a>
  {% endif %}
</nav>
{%- endmacro %}

{% macro collection_card(site, collection) -%}
<article class="collection-card story-step">
  <p class="data-label">
    {{ collection.pages | length }} {{ site.extension_setting('i18n', 'label_reports', 'reports') }}
  </p>
  <h3><a href="{{ collection.root_href() }}">{{ collection.title }}</a></h3>
  <ol>
    {% for page in collection.pages %}
      <li>
        <a href="{{ collection.output_slug }}/{{ page.file_name() }}">{{ page.title }}</a>
      </li>
    {% endfor %}
  </ol>
</article>
{%- endmacro %}
""".strip()


PAGE_TEMPLATE = """
{% import 'parts.html' as ui %}
<!doctype html>
<html lang="{{ rendered_page.site.html_language() }}">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{{ rendered_page.site.description }}">
    <title>{{ rendered_page.page.title }} - {{ rendered_page.collection.title }}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="../assets/site.css">
    <script src="../assets/site.js" defer></script>
  </head>
  <body data-theme="editorial-lab">
    <a class="skip-link" href="#main-content">Skip to content</a>
    {{ ui.site_header(rendered_page.site, rendered_page.navigation, rendered_page.language_links) }}
    <div class="site-shell article-layout">
      {{ ui.site_navigation(rendered_page.site, rendered_page.navigation) }}
      <main class="content" id="main-content" tabindex="-1">
        <article class="article" data-page-slug="{{ rendered_page.page.slug }}">
          <header class="article-header story-step">
            <p class="eyebrow">{{ rendered_page.collection.title }}</p>
            <h1>{{ rendered_page.article.title }}</h1>
            {% set article_lede = rendered_page.site.extension_setting(
              'i18n',
              'article_lede',
              'A field report for reproducible machine-learning systems.',
            ) %}
            <p class="lede">{{ article_lede }}</p>
          </header>
          <div class="article-body stack">{{ rendered_page.article.body | safe }}</div>
        </article>
        {{ ui.pager(rendered_page) }}
      </main>
      {{ ui.article_toc(rendered_page.site, rendered_page.article) }}
    </div>
    {{ ui.site_footer(rendered_page.site) }}
  </body>
</html>
""".strip()


INDEX_TEMPLATE = """
{% import 'parts.html' as ui %}
<!doctype html>
<html lang="{{ rendered_index.site.html_language() }}">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{{ rendered_index.site.description }}">
    <title>{{ rendered_index.site.title }}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="assets/site.css">
    <script src="assets/site.js" defer></script>
  </head>
  <body data-theme="editorial-lab">
    <a class="skip-link" href="#main-content">Skip to content</a>
    {{ ui.site_header(
      rendered_index.site,
      rendered_index.navigation,
      rendered_index.language_links,
    ) }}
    <div class="site-shell sidebar-layout">
      {{ ui.site_navigation(rendered_index.site, rendered_index.navigation, True) }}
      <main class="content" id="main-content" tabindex="-1">
        <section class="hero story-step" aria-labelledby="site-heading">
          {% set hero_eyebrow = rendered_index.site.extension_setting(
            'i18n',
            'hero_eyebrow',
            'Editorial machine-learning atlas',
          ) %}
          <p class="eyebrow">{{ hero_eyebrow }}</p>
          <h1 id="site-heading">{{ rendered_index.site.title }}</h1>
          <p class="lede">{{ rendered_index.site.description }}</p>
        </section>
        <section class="collection-grid" aria-labelledby="collections-heading">
          <div class="section-heading cluster">
            {% set dispatches_label = rendered_index.site.extension_setting(
              'i18n',
              'label_dispatches',
              'Dispatches',
            ) %}
            {% set projects_label = rendered_index.site.extension_setting(
              'i18n',
              'label_projects',
              'Projects',
            ) %}
            <p class="data-label">{{ dispatches_label }}</p>
            <h2 id="collections-heading">{{ projects_label }}</h2>
          </div>
          <div class="cards">
            {% for collection in rendered_index.collections %}
              {{ ui.collection_card(rendered_index.site, collection) }}
            {% endfor %}
          </div>
        </section>
      </main>
    </div>
    {{ ui.site_footer(rendered_index.site) }}
  </body>
</html>
""".strip()
