TEMPLATE_PARTS = """
{% macro site_header(site, navigation) -%}
<header class="site-header">
  <div class="masthead-mark" aria-hidden="true">ML</div>
  <div class="masthead-copy">
    <a class="site-title" href="{{ navigation.home_href }}">{{ site.title }}</a>
    <p class="site-description">{{ site.description }}</p>
  </div>
  <button
    class="menu-toggle"
    type="button"
    aria-controls="site-navigation"
    aria-expanded="false"
  >
    Menu
  </button>
</header>
{%- endmacro %}

{% macro site_navigation(navigation, home_current=False) -%}
<aside class="sidebar" id="site-navigation">
  <nav aria-label="Primary">
    <a
      class="home-link"
      href="{{ navigation.home_href }}"
      {% if home_current %}aria-current="page"{% endif %}
    >
      Field Index
    </a>
    {% for section in navigation.sections %}
      <section class="navigation-section" aria-labelledby="section-{{ loop.index }}">
        <h2 id="section-{{ loop.index }}">
          <a href="{{ section.href }}">{{ section.title }}</a>
        </h2>
        <nav aria-label="{{ section.title }} contents">
          <ol>
            {% for link in section.links %}
              <li>
                <a href="{{ link.href }}"{% if link.current %} aria-current="page"{% endif %}>
                  {{ link.label }}
                </a>
              </li>
            {% endfor %}
          </ol>
        </nav>
      </section>
    {% endfor %}
  </nav>
</aside>
{%- endmacro %}

{% macro site_footer() -%}
<footer class="site-footer">
  <p>Generated by the content-first static site generator.</p>
</footer>
{%- endmacro %}

{% macro pager(rendered_page) -%}
<nav class="pager" aria-label="Adjacent pages">
  {% if rendered_page.previous_link %}
    <a rel="prev" href="{{ rendered_page.previous_link.href }}">
      <span>{{ rendered_page.previous_link.relation }}</span>
      {{ rendered_page.previous_link.label }}
    </a>
  {% endif %}
  {% if rendered_page.next_link %}
    <a rel="next" href="{{ rendered_page.next_link.href }}">
      <span>{{ rendered_page.next_link.relation }}</span>
      {{ rendered_page.next_link.label }}
    </a>
  {% endif %}
</nav>
{%- endmacro %}

{% macro collection_card(collection) -%}
<article class="collection-card story-step">
  <p class="data-label">{{ collection.pages | length }} reports</p>
  <h3><a href="{{ collection.root_href() }}">{{ collection.title }}</a></h3>
  <ol>
    {% for page in collection.pages %}
      <li>
        <a href="{{ collection.output_slug }}/{{ page.file_name() }}">{{ page.title }}</a>
      </li>
    {% endfor %}
  </ol>
</article>
{%- endmacro %}
""".strip()


PAGE_TEMPLATE = """
{% import 'parts.html' as ui %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{{ rendered_page.site.description }}">
    <title>{{ rendered_page.page.title }} - {{ rendered_page.collection.title }}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="../assets/site.css">
    <script src="../assets/site.js" defer></script>
  </head>
  <body data-theme="editorial-lab">
    <a class="skip-link" href="#main-content">Skip to content</a>
    {{ ui.site_header(rendered_page.site, rendered_page.navigation) }}
    <div class="site-shell sidebar-layout">
      {{ ui.site_navigation(rendered_page.navigation) }}
      <main class="content" id="main-content" tabindex="-1">
        <article class="article" data-page-slug="{{ rendered_page.page.slug }}">
          <header class="article-header story-step">
            <p class="eyebrow">{{ rendered_page.collection.title }}</p>
            <h1>{{ rendered_page.article.title }}</h1>
            <p class="lede">A field report for reproducible machine-learning systems.</p>
          </header>
          <div class="article-body stack">{{ rendered_page.article.body | safe }}</div>
        </article>
        {{ ui.pager(rendered_page) }}
      </main>
    </div>
    {{ ui.site_footer() }}
  </body>
</html>
""".strip()


INDEX_TEMPLATE = """
{% import 'parts.html' as ui %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{{ rendered_index.site.description }}">
    <title>{{ rendered_index.site.title }}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="assets/site.css">
    <script src="assets/site.js" defer></script>
  </head>
  <body data-theme="editorial-lab">
    <a class="skip-link" href="#main-content">Skip to content</a>
    {{ ui.site_header(rendered_index.site, rendered_index.navigation) }}
    <div class="site-shell sidebar-layout">
      {{ ui.site_navigation(rendered_index.navigation, True) }}
      <main class="content" id="main-content" tabindex="-1">
        <section class="hero story-step" aria-labelledby="site-heading">
          <p class="eyebrow">Editorial machine-learning atlas</p>
          <h1 id="site-heading">{{ rendered_index.site.title }}</h1>
          <p class="lede">{{ rendered_index.site.description }}</p>
        </section>
        <section class="collection-grid" aria-labelledby="collections-heading">
          <div class="section-heading cluster">
            <p class="data-label">Dispatches</p>
            <h2 id="collections-heading">Projects</h2>
          </div>
          <div class="cards">
            {% for collection in rendered_index.collections %}
              {{ ui.collection_card(collection) }}
            {% endfor %}
          </div>
        </section>
      </main>
    </div>
    {{ ui.site_footer() }}
  </body>
</html>
""".strip()
