"""Evidence recorder shared by the Athena parity notebooks.

Each notebook calls ``record`` once per feature probe — ``PASS`` means the
behavior matches real Athena, ``FAIL`` a shipped feature is broken, ``GAP`` a
probed boundary is absent — prints ``render`` for the session matrix, and
persists it with ``persist``, which writes ``parity/<name>.md`` and
regenerates the consolidated ``PARITY.md`` at the project root.

Example:
    >>> from _evidence import EVIDENCE, persist, record, render
    >>> record("endpoint routing", "PASS", "athena→:5001 s3→:5000", 12.0)
    >>> print(render())
    >>> persist("01_smoke_and_endpoints")
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

_STATUSES = ("PASS", "FAIL", "GAP")

PROJECT_DIR = Path(__file__).resolve().parents[1]


@dataclass(frozen=True)
class Evidence:
    """One measured outcome for a single feature probe."""

    feature: str
    status: str
    detail: str
    latency_ms: float | None = None


EVIDENCE: list[Evidence] = []


def record(
    feature: str, status: str, detail: str, latency_ms: float | None = None
) -> Evidence:
    """Append one measured outcome; ``status`` must be PASS, FAIL, or GAP."""
    if status not in _STATUSES:
        raise ValueError(
            f"status {status!r} is not one of {_STATUSES}; "
            "expected 'PASS', 'FAIL', or 'GAP'"
        )
    row = Evidence(
        feature=feature, status=status, detail=detail, latency_ms=latency_ms
    )
    EVIDENCE.append(row)
    return row


def render(rows: list[Evidence] | None = None) -> str:
    """Render evidence rows as a markdown table for the matrix cell."""
    if rows is None:
        rows = EVIDENCE
    header = [
        "| feature | status | detail | latency_ms |",
        "|---|---|---|---|",
    ]
    body = [_row_line(row) for row in rows]
    return "\n".join(header + body) + "\n"


def persist(name: str, rows: list[Evidence] | None = None) -> Path:
    """Write ``parity/<name>.md`` and regenerate ``PARITY.md``."""
    parity_dir = PROJECT_DIR / "parity"
    parity_dir.mkdir(exist_ok=True)
    fragment = parity_dir / f"{name}.md"
    fragment.write_text(f"## {name}\n\n{render(rows)}")
    index = "\n".join(
        part.read_text() for part in sorted(parity_dir.glob("*.md"))
    )
    index_path = PROJECT_DIR / "PARITY.md"
    index_path.write_text(
        "# Athena emulator parity evidence\n\n"
        "Generated by the parity notebooks; do not edit by hand.\n\n" + index
    )
    return fragment


def _row_line(row: Evidence) -> str:
    latency = "" if row.latency_ms is None else f"{row.latency_ms:.0f}"
    detail = row.detail.replace("|", "\\|").replace("\n", " ")
    return f"| {row.feature} | {row.status} | {detail} | {latency} |"
