"""Evidence recorder shared by the Athena parity notebooks.

Each notebook calls ``record`` once per feature probe — ``PASS`` means the
behavior matches real Athena, ``FAIL`` a shipped feature is broken, ``GAP`` a
probed boundary is absent — prints ``render`` for the session matrix, and
persists it with ``persist``, which writes ``parity/<name>.md`` and
regenerates the consolidated ``PARITY.md`` at the project root.

Example:
    >>> from _evidence import EVIDENCE, persist, record, render
    >>> record("endpoint routing", "PASS", "athena→:5001 s3→:5000", 12.0)
    >>> print(render())
    >>> persist("01_smoke_and_endpoints")
"""

from __future__ import annotations

import contextlib
import fcntl
import hashlib
import os
import re
import tempfile
from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path

_STATUSES = ("PASS", "FAIL", "GAP")
_NAME_SLUG = re.compile(r"[a-z0-9_-]+")

PROJECT_DIR = Path(__file__).resolve().parents[1]


@dataclass(frozen=True)
class Evidence:
    """One measured outcome for a single feature probe."""

    feature: str
    status: str
    detail: str
    latency_ms: float | None = None

    def __post_init__(self) -> None:
        for field_name in ("feature", "status", "detail"):
            value = getattr(self, field_name)
            if not isinstance(value, str):
                raise TypeError(
                    f"{field_name} must be str, got {value!r} ({type(value).__name__})"
                )
        if self.status not in _STATUSES:
            raise ValueError(
                f"status {self.status!r} is not one of {_STATUSES}; "
                "expected 'PASS', 'FAIL', or 'GAP'"
            )


EVIDENCE: list[Evidence] = []


def record(
    feature: str, status: str, detail: str, latency_ms: float | None = None
) -> Evidence:
    """Append one measured outcome; ``status`` must be PASS, FAIL, or GAP."""
    row = Evidence(
        feature=feature, status=status, detail=detail, latency_ms=latency_ms
    )
    EVIDENCE.append(row)
    return row


def render(rows: list[Evidence] | None = None) -> str:
    """Render evidence rows as a markdown table for the matrix cell.

    Rows are deduplicated per ``(feature, status, detail)`` keeping the
    latest occurrence, so re-executing a probe cell in a live kernel replaces
    the earlier outcome instead of accumulating a second copy.
    """
    if rows is None:
        rows = EVIDENCE
    header = [
        "| feature | status | detail | latency_ms |",
        "|---|---|---|---|",
    ]
    body = [_row_line(row) for row in _latest_per_probe(rows)]
    return "\n".join(header + body) + "\n"


def persist(name: str, rows: list[Evidence] | None = None) -> Path:
    """Write ``parity/<name>.md`` and regenerate ``PARITY.md``.

    ``name`` must match ``^[a-z0-9_-]+$`` (the notebook file's stem).
    Fragments whose stem has no ``notebooks/<stem>.ipynb`` are dropped from
    the index. The whole write runs under a cross-process file lock so
    concurrent notebook kernels cannot overwrite each other's sections.
    """
    if _NAME_SLUG.fullmatch(name) is None:
        raise ValueError(
            f"persist name {name!r} is not a valid slug; "
            "expected ^[a-z0-9_-]+$"
        )
    parity_dir = PROJECT_DIR / "parity"
    parity_dir.mkdir(exist_ok=True)
    fragment = parity_dir / f"{name}.md"
    with _persist_lock():
        _write_atomic(fragment, f"## {name}\n\n{render(rows)}")
        _drop_orphan_fragments(parity_dir)
        _write_atomic(PROJECT_DIR / "PARITY.md", _index_text(parity_dir))
    return fragment


def _latest_per_probe(rows: list[Evidence]) -> list[Evidence]:
    kept: dict[tuple[str, str, str], Evidence] = {}
    for row in rows:
        kept[(row.feature, row.status, row.detail)] = row
    return list(kept.values())


@contextlib.contextmanager
def _persist_lock() -> Iterator[None]:
    digest = hashlib.sha256(str(PROJECT_DIR).encode()).hexdigest()[:16]
    lock_path = Path(tempfile.gettempdir()) / f"athena-parity-{digest}.lock"
    with lock_path.open("w") as lock_file:
        fcntl.flock(lock_file, fcntl.LOCK_EX)
        yield


def _write_atomic(path: Path, text: str) -> None:
    tmp = path.with_name(f"{path.name}.tmp")
    tmp.write_text(text)
    os.replace(tmp, path)


def _drop_orphan_fragments(parity_dir: Path) -> None:
    notebooks_dir = PROJECT_DIR / "notebooks"
    if not notebooks_dir.is_dir():
        return
    stems = {notebook.stem for notebook in notebooks_dir.glob("*.ipynb")}
    for fragment in parity_dir.glob("*.md"):
        if fragment.stem not in stems:
            fragment.unlink()


def _index_text(parity_dir: Path) -> str:
    index = "\n".join(
        part.read_text() for part in sorted(parity_dir.glob("*.md"))
    )
    return (
        "# Athena emulator parity evidence\n\n"
        "Generated by the parity notebooks; do not edit by hand.\n\n" + index
    )


def _row_line(row: Evidence) -> str:
    latency = "" if row.latency_ms is None else f"{row.latency_ms:g}"
    feature = _escape_cell(row.feature)
    detail = _escape_cell(row.detail)
    return f"| {feature} | {row.status} | {detail} | {latency} |"


def _escape_cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")
