from jinja2 import Environment, StrictUndefined

from ssg.application.ports import PageRenderer
from ssg.domain.site import RenderedIndex, RenderedPage


class JinjaPageRenderer(PageRenderer):
    def __init__(self) -> None:
        self._environment = Environment(autoescape=True, undefined=StrictUndefined)
        self._page_template = self._environment.from_string(PAGE_TEMPLATE)
        self._index_template = self._environment.from_string(INDEX_TEMPLATE)

    def render_page(self, rendered_page: RenderedPage) -> str:
        return self._page_template.render(rendered_page=rendered_page)

    def render_index(self, rendered_index: RenderedIndex) -> str:
        return self._index_template.render(rendered_index=rendered_index)

    def assets(self) -> dict[str, str]:
        return {"site.css": SITE_CSS, "site.js": SITE_JS}


PAGE_TEMPLATE = """
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{{ rendered_page.site.description }}">
    <title>{{ rendered_page.page.title }} - {{ rendered_page.collection.title }}</title>
    <link rel="stylesheet" href="../assets/site.css">
    <script src="../assets/site.js" defer></script>
  </head>
  <body>
    <a class="skip-link" href="#main-content">Skip to content</a>
    <header class="site-header">
      <div>
        <a class="site-title" href="{{ rendered_page.navigation.home_href }}">
          {{ rendered_page.site.title }}
        </a>
        <p class="site-description">{{ rendered_page.site.description }}</p>
      </div>
      <button
        class="menu-toggle"
        type="button"
        aria-controls="site-navigation"
        aria-expanded="false"
      >
        Menu
      </button>
    </header>
    <div class="site-shell">
      <aside class="sidebar" id="site-navigation">
        <nav aria-label="Primary">
          <a class="home-link" href="{{ rendered_page.navigation.home_href }}">All projects</a>
          {% for section in rendered_page.navigation.sections %}
            <section class="navigation-section" aria-labelledby="section-{{ loop.index }}">
              <h2 id="section-{{ loop.index }}">
                <a href="{{ section.href }}">{{ section.title }}</a>
              </h2>
              <nav aria-label="{{ section.title }} contents">
                <ol>
                  {% for link in section.links %}
                    <li>
                      <a href="{{ link.href }}"{% if link.current %} aria-current="page"{% endif %}>
                        {{ link.label }}
                      </a>
                    </li>
                  {% endfor %}
                </ol>
              </nav>
            </section>
          {% endfor %}
        </nav>
      </aside>
      <main class="content" id="main-content" tabindex="-1">
        <article class="article" data-page-slug="{{ rendered_page.page.slug }}">
          <header class="article-header">
            <p class="eyebrow">{{ rendered_page.collection.title }}</p>
            <h1>{{ rendered_page.article.title }}</h1>
          </header>
          <div class="article-body">{{ rendered_page.article.body | safe }}</div>
        </article>
        <nav class="pager" aria-label="Adjacent pages">
          {% if rendered_page.previous_link %}
            <a rel="prev" href="{{ rendered_page.previous_link.href }}">
              <span>{{ rendered_page.previous_link.relation }}</span>
              {{ rendered_page.previous_link.label }}
            </a>
          {% endif %}
          {% if rendered_page.next_link %}
            <a rel="next" href="{{ rendered_page.next_link.href }}">
              <span>{{ rendered_page.next_link.relation }}</span>
              {{ rendered_page.next_link.label }}
            </a>
          {% endif %}
        </nav>
      </main>
    </div>
    <footer class="site-footer">
      <p>Generated by the content-first static site generator.</p>
    </footer>
  </body>
</html>
""".strip()


INDEX_TEMPLATE = """
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{{ rendered_index.site.description }}">
    <title>{{ rendered_index.site.title }}</title>
    <link rel="stylesheet" href="assets/site.css">
    <script src="assets/site.js" defer></script>
  </head>
  <body>
    <a class="skip-link" href="#main-content">Skip to content</a>
    <header class="site-header">
      <div>
        <a class="site-title" href="{{ rendered_index.navigation.home_href }}">
          {{ rendered_index.site.title }}
        </a>
        <p class="site-description">{{ rendered_index.site.description }}</p>
      </div>
      <button
        class="menu-toggle"
        type="button"
        aria-controls="site-navigation"
        aria-expanded="false"
      >
        Menu
      </button>
    </header>
    <div class="site-shell">
      <aside class="sidebar" id="site-navigation">
        <nav aria-label="Primary">
          <a class="home-link" href="{{ rendered_index.navigation.home_href }}" aria-current="page">
            All projects
          </a>
          {% for section in rendered_index.navigation.sections %}
            <section class="navigation-section" aria-labelledby="section-{{ loop.index }}">
              <h2 id="section-{{ loop.index }}">
                <a href="{{ section.href }}">{{ section.title }}</a>
              </h2>
              <nav aria-label="{{ section.title }} contents">
                <ol>
                  {% for link in section.links %}
                    <li><a href="{{ link.href }}">{{ link.label }}</a></li>
                  {% endfor %}
                </ol>
              </nav>
            </section>
          {% endfor %}
        </nav>
      </aside>
      <main class="content" id="main-content" tabindex="-1">
        <section class="hero" aria-labelledby="site-heading">
          <p class="eyebrow">Content-first learning site</p>
          <h1 id="site-heading">{{ rendered_index.site.title }}</h1>
          <p>{{ rendered_index.site.description }}</p>
        </section>
        <section class="collection-grid" aria-labelledby="collections-heading">
          <h2 id="collections-heading">Projects</h2>
          <div class="cards">
            {% for collection in rendered_index.collections %}
              <article class="collection-card">
                <h3><a href="{{ collection.root_href() }}">{{ collection.title }}</a></h3>
                <p>{{ collection.pages | length }} learning pages</p>
                <ol>
                  {% for page in collection.pages %}
                    <li>
                      <a href="{{ collection.output_slug }}/{{ page.file_name() }}">
                        {{ page.title }}
                      </a>
                    </li>
                  {% endfor %}
                </ol>
              </article>
            {% endfor %}
          </div>
        </section>
      </main>
    </div>
    <footer class="site-footer">
      <p>Generated by the content-first static site generator.</p>
    </footer>
  </body>
</html>
""".strip()


SITE_CSS = """
:root {
  color-scheme: light;
  --background: #f8fafc;
  --surface: #ffffff;
  --surface-muted: #eef2f7;
  --text: #102033;
  --muted: #526173;
  --border: #d6dee9;
  --accent: #2257d6;
  --accent-strong: #183f9c;
  --focus: #ffbf47;
  --shadow: 0 24px 70px rgb(15 23 42 / 0.08);
  font-family:
    Inter,
    ui-sans-serif,
    system-ui,
    -apple-system,
    BlinkMacSystemFont,
    "Segoe UI",
    sans-serif;
}

* { box-sizing: border-box; }

body {
  margin: 0;
  background: var(--background);
  color: var(--text);
  font-size: 1rem;
  line-height: 1.65;
}

a { color: var(--accent); text-decoration-thickness: 0.08em; text-underline-offset: 0.18em; }
a:hover { color: var(--accent-strong); }
a:focus-visible, button:focus-visible { outline: 3px solid var(--focus); outline-offset: 3px; }

.skip-link {
  position: absolute;
  left: 1rem;
  top: 1rem;
  z-index: 20;
  transform: translateY(-160%);
  background: var(--text);
  color: white;
  padding: 0.7rem 1rem;
  border-radius: 999px;
}

.skip-link:focus { transform: translateY(0); }

.site-header {
  align-items: center;
  background: rgb(255 255 255 / 0.92);
  border-bottom: 1px solid var(--border);
  display: flex;
  gap: 1rem;
  justify-content: space-between;
  padding: 1rem clamp(1rem, 4vw, 3rem);
  position: sticky;
  top: 0;
  z-index: 10;
}

.site-title { color: var(--text); font-size: 1.1rem; font-weight: 800; text-decoration: none; }
.site-description { color: var(--muted); margin: 0.15rem 0 0; max-width: 62ch; }

.menu-toggle {
  background: var(--text);
  border: 0;
  border-radius: 999px;
  color: white;
  cursor: pointer;
  display: none;
  font: inherit;
  padding: 0.65rem 1rem;
}

.site-shell {
  display: grid;
  grid-template-columns: minmax(16rem, 20rem) minmax(0, 1fr);
  gap: clamp(1.5rem, 4vw, 3rem);
  margin: 0 auto;
  max-width: 92rem;
  padding: clamp(1rem, 3vw, 2rem);
}

.sidebar {
  align-self: start;
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 1.25rem;
  box-shadow: var(--shadow);
  max-height: calc(100vh - 7rem);
  overflow: auto;
  padding: 1rem;
  position: sticky;
  top: 6rem;
}

.home-link,
.navigation-section a {
  border-radius: 0.75rem;
  display: block;
  padding: 0.45rem 0.6rem;
}
.home-link { font-weight: 800; margin-bottom: 0.8rem; text-decoration: none; }
.navigation-section { border-top: 1px solid var(--border); padding: 0.9rem 0 0; }
.navigation-section h2 { font-size: 0.95rem; margin: 0 0 0.35rem; }
.navigation-section ol { list-style: none; margin: 0; padding: 0; }
.navigation-section li { margin: 0.1rem 0; }
.navigation-section a[aria-current="page"], .home-link[aria-current="page"] {
  background: var(--surface-muted);
  color: var(--accent-strong);
  font-weight: 800;
  text-decoration: none;
}

.content { min-width: 0; }
.hero, .article, .collection-card {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 1.5rem;
  box-shadow: var(--shadow);
}

.hero { margin-bottom: 1.5rem; padding: clamp(1.5rem, 4vw, 3rem); }
.hero h1,
.article h1 {
  font-size: clamp(2rem, 6vw, 4rem);
  line-height: 1.05;
  margin: 0.2rem 0 1rem;
}
.hero p, .article-header p { color: var(--muted); max-width: 72ch; }
.eyebrow {
  color: var(--accent-strong);
  font-size: 0.8rem;
  font-weight: 900;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}

.article { overflow: hidden; }
.article-header { border-bottom: 1px solid var(--border); padding: clamp(1.5rem, 4vw, 3rem); }
.article-body { padding: clamp(1.5rem, 4vw, 3rem); }
.article-body > * { max-width: 76ch; }
.article-body img, .article-body video { border-radius: 1rem; height: auto; max-width: 100%; }
.article-body pre {
  background: #0f172a;
  border-radius: 1rem;
  color: #e2e8f0;
  max-width: 100%;
  overflow: auto;
  padding: 1rem;
}
.article-body code { font-family: "SFMono-Regular", Consolas, "Liberation Mono", monospace; }

.collection-grid h2 { margin: 0 0 1rem; }
.cards { display: grid; gap: 1rem; grid-template-columns: repeat(auto-fit, minmax(18rem, 1fr)); }
.collection-card { padding: 1.25rem; }
.collection-card h3 { margin-top: 0; }
.collection-card ol { padding-left: 1.3rem; }

.pager {
  display: grid;
  gap: 1rem;
  grid-template-columns: repeat(auto-fit, minmax(14rem, 1fr));
  margin-top: 1rem;
}
.pager a {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 1rem;
  box-shadow: var(--shadow);
  color: var(--text);
  padding: 1rem;
  text-decoration: none;
}
.pager span { color: var(--muted); display: block; font-size: 0.85rem; }

.site-footer { color: var(--muted); padding: 1rem clamp(1rem, 4vw, 3rem) 2rem; text-align: center; }

@media (max-width: 52rem) {
  .menu-toggle { display: inline-flex; }
  .site-shell { display: block; }
  .sidebar { display: none; margin-bottom: 1rem; max-height: none; position: static; }
  .sidebar.is-open { display: block; }
}

@media (prefers-reduced-motion: no-preference) {
  .skip-link { transition: transform 160ms ease; }
}
""".strip()


SITE_JS = """
const menuButton = document.querySelector('.menu-toggle');
const navigation = document.querySelector('#site-navigation');

if (menuButton instanceof HTMLButtonElement && navigation instanceof HTMLElement) {
  menuButton.addEventListener('click', () => {
    const expanded = menuButton.getAttribute('aria-expanded') === 'true';
    menuButton.setAttribute('aria-expanded', String(!expanded));
    navigation.classList.toggle('is-open', !expanded);
  });
}
""".strip()
